Repository bloomberg/pystack, pull requests merged in 2023-04, with the labels that each got.

#42 typo: Remove references to `memray`
  .github/ISSUE_TEMPLATE/---feature-request.yaml
  .github/ISSUE_TEMPLATE/config.yml
  NEWS.rst
Labels: documentation

#68 ci: Add sanity-check workflow: require DCO and news entry
  .github/workflows/sanity-check.yml
Labels: skip news

#74 Only delete the '*.so' that we create
  Makefile
Labels: skip news

#75 Remove `extras-requires`
  Makefile
  setup.py
Labels: enhancement, skip news

#79 Reach 100% python coverage rate
  Makefile
  pyproject.toml
  src/pystack/maps.py
  tests/integration/test_gather_stacks.py
  tests/unit/test_main.py
  tests/unit/test_maps.py
  tests/unit/test_process.py
Labels: skip news

#89 tests: Fix a typo copy-pasted across several tests
  tests/unit/test_maps.py
Labels: skip news

#92 Fix a Python 3.7 incompatibility
  news/92.bugfix.rst
  src/pystack/maps.py
Labels: bug
