Repository bloomberg/pystack, pull requests merged in 2023-08, with the labels that each got.

#130 Fix typo
  docs/_templates/index.html
Labels: documentation, skip news

#133 ci: Allow publishing Python 3.12 wheels
  .github/workflows/build_wheels.yml
Labels: skip news

#135 Stop telling setuptools our headers are in src/
  setup.py
Labels: bug, skip news

#141 Remove --self flag
  README.md
  src/pystack/__main__.py
Labels: skip news
